-- بذر بيانات المتابعة الأولية (مولّد آلياً من data/data.json)
PRAGMA foreign_keys = ON;

-- الشركات / المنشآت
INSERT INTO companies (id, name, cr_number, mol_number, notes) VALUES (1, 'الشركة المحلية للتجارة والزراعة المحدودة', NULL, '1-164199', '');
INSERT INTO companies (id, name, cr_number, mol_number, notes) VALUES (2, 'الشركة المحلية الدولية التجارية', NULL, '1-1516125', '');
INSERT INTO companies (id, name, cr_number, mol_number, notes) VALUES (3, 'مصنع نبات الأرض', NULL, '1-2187821', '');

-- الموظفون / الإقامات
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('AHMED GANI MOHAMMED HAZI', '2459407488', 1, '2026-09-28', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('RIDUY RUPAN  MIAH', '2522883194', 1, '2026-08-02', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ZAGIRHOSSAIN   ABDULMALEK', '2144633787', 1, '2026-10-14', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('كمال محمد عبد ربه اغريب', '2565259484', 1, '2026-07-05', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('انس نصر علي فرح', '2342412182', 1, '2026-08-20', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('محمد أشرف فوزى سمك', '2335331688', 1, '2026-08-05', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('عبدالرحمن خلف معوض معوض', '2604662862', 1, '2026-07-06', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('KADENGAL - - ABDURAHIMAN', '2088725458', 1, '2026-11-09', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('محمد فرحان محمد علي', '2611944162', 1, '2026-10-05', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('علي كامل محمد سليمان', '2161722299', 1, '2026-09-16', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('محمد محمود فقير محمد', '2177796964', 1, '2026-10-06', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('فيصل عصام موسى بشيتي', '2217466248', 1, '2026-08-08', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('شعبان محمد شعبان مكي', '2208886842', 1, '2027-05-15', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MOHAMMED SEAM  MOHAMMED', '2193827231', 1, '2026-08-15', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('احمد منشاوى عباس العطوى', '2593975085', 1, '2027-02-20', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('BHEEM SHANKAR   DHARMRAJ', '2611943529', 1, '2026-07-13', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('نائل عايش عبدالرحمن خليل', '2136199037', 1, '2026-07-14', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('JAN   SARIF', '2438155562', 1, '2028-06-17', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('اشرف طاهر نعيم هاشم', '2530613906', 1, '2027-03-06', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('محمد عبد العليم على فوده', '2242844682', 1, '2027-08-01', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ARJUN KUMAR  VISHVAKARMA', '2408618375', 1, '2026-11-29', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('عبدالمبدى عبدالموجود عبدالمبدى محمد', '2505013256', 1, '2026-12-22', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MOHAMED ABDUL  HALEEM', '2301029795', 1, '2026-11-02', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('اوميد عوض محمد عبدالرافع', '2290437744', 1, '2026-08-04', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('عثمان محمد عثمان محمد', '2411677491', 1, '2027-05-30', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('SALIMHOSSAIN   SHAHIDULLAH', '2096368705', 1, '2027-02-14', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ساليم مياه عبد الجليل', '2196053330', 1, '2026-10-16', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MOHAMMAD   RAFIK', '2555586672', 3, '2026-11-01', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('SHAMIM HOSSEN  MEHADI', '2524155773', 3, '2026-11-18', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('RAHAT   RAYHAN', '2468333972', 3, '2026-08-12', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ABDUL KHALIQ  MOHAMMED', '2579206513', 3, '2027-03-22', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MD RAKIB  HOSSAIN', '2536447770', 3, '2027-01-03', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('NAZEER ALI BIN  KHADER', '2578800100', 3, '2026-09-10', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ALAMSHER SIKANDER  ALI', '2578011344', 3, '2026-08-23', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('NUR   ISLAM', '2432095814', 3, '2027-04-08', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ABDUL KABIR KHAN MUHAMMAD AZEEM KHAN', '2547493748', 3, '2026-08-03', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ABUBAKER SIDDIQ SAYYAD', '2570772372', 1, '2025-05-20', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('ISMAIL SANU  MIAH', '2496886009', 3, '2027-05-21', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MOHAMMAD YASIN AHAMAD  EMON', '2588057477', 3, '2027-04-11', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MOHAMED SHABBIR   HUSSAIN', '2140041415', 2, '2027-06-20', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('مجدي ميرغني حسن التوم', '2101982441', 2, '2026-11-14', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('احمد زيدان زكي حسين', '2092318928', 2, '2026-10-06', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('احمد كامل احمد السيد', '2558230377', 2, '2027-03-13', '');
INSERT INTO employees (name, iqama_number, company_id, iqama_expiry, notes) VALUES ('MOHAMMAD MUNTAKA MUSALMAN MOHAMMAD', '2325590459', 2, '2027-05-04', '');

-- التراخيص والسجلات
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'ترخيص بلدي المستودع في حي طيبة', NULL, 'بلدي', '2028-12-03', '15/10/1449', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'ترخيص الدفاع المدني لمستودع حي طيبة', NULL, 'سلامة', '2028-12-03', '15/10/1449', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'ترخيص بلدي لمكتب رقم 17109', NULL, 'بلدي', '2026-07-29', '13/02/1448', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'ترخيص بلدي لمكتب 17103', NULL, 'بلدي', '2026-03-30', '11/10/1447', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'شهادة السجل التجادي ( التأكيد السنوي )', NULL, 'المركز السعدوي للأعمال', '2026-08-20', '07/03/1448', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'sts', NULL, '', NULL, '', '25/ من كل شهر', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'مقيم', NULL, '', '2027-03-19', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'منصة تم', NULL, '', NULL, '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'التأمين الطبي', NULL, '', '2026-10-29', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'النقل الثقيل للبضائع', NULL, '', '2029-09-17', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (1, 'منصة قوى', NULL, 'قوى', '2026-12-31', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (2, 'ترخيص بلدي مكتب رقم 17101', NULL, '', '2029-11-12', '04/08/1451', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (2, 'شهادة السجل التجاري ( التأكيد السنوي )', NULL, 'المركز السعودي للأعمال', '2026-11-18', '08/06/1448', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (2, 'قوى', NULL, 'قوى', '2027-04-07', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (2, 'sts', NULL, 'STS', NULL, '', '25/ من كل شهر', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (2, 'مقيم', NULL, 'مقيم', '2026-09-07', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'اشهادة لسجل التجاري  ( التأكيد السنوي )', NULL, 'المركز السعودي للأعمال', '2027-04-20', '13/11/1448', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'رخصة تشغيل المصنع', NULL, '', '2027-03-26', '17/10/1448', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'ترخيص منشأة', NULL, '', '2028-03-04', '08/11/1449', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'التأمين على المصنع شركة ميدغلف للتأمين التعاوني', NULL, 'شركة ميد غلف', '2026-09-10', '26/04/1448', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'عقد نفايات المصنع', NULL, '', '2027-06-14', '09/01/1449', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'قوى', NULL, '', '2026-12-31', '', '', '');
INSERT INTO licenses (company_id, title, license_number, issuer, expiry, hijri_expiry, recurring_note, notes) VALUES (3, 'التصريح البيئي', NULL, '', '2027-10-07', '05/02/1449', '', '');

-- المركبات
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('نيسان ارمادا', 'ب ب م 6580', 1, '2024-10-25', '1446-04-22', '2023-11-25', '1445-05-11', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ب ل 1620', 1, '2028-12-30', '1450-08-14', '2027-02-03', '1448-08-26', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('هونداي هاتشباك', 'ح ب د 2549', 1, '2028-02-03', '1449-09-07', '2026-06-18', '1448-01-03', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب س ح 1013', 1, '2026-07-03', '1448-01-18', '2026-12-08', '1448-06-28', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غماره', 'أ ب ل 5799', 1, '2025-07-02', '1447-01-07', '2024-06-22', '1445-12-16', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو شاحنه', 'ب ع أ 2151', 1, '2027-04-22', '1448-11-15', '2027-02-26', '1448-09-19', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ب ل 1621', 1, '2028-12-30', '1450-08-14', '2026-07-07', '1448-01-22', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('هيونداي حافلة', 'ب ع ب 2633', 1, '2027-05-10', '1448-12-04', '2027-03-01', '1448-09-22', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ع أ 2264', 1, '2027-04-22', '1448-11-15', '2027-02-24', '1448-09-17', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ب ل 1619', 1, '2026-02-02', '1447-08-14', '2026-07-17', '1448-02-03', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غماره', 'ب ع أ 2152', 1, '2027-04-22', '1448-11-15', '2027-03-01', '1448-09-22', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('هونداي سنتافيه', 'ب ن ح 4509', 1, '2026-12-02', '1448-06-22', '2026-06-29', '1448-01-14', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('هونداي توسان', 'ب ن م 9987', 1, '2027-01-28', '1448-08-20', '2026-10-13', '1448-05-02', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('متسوبيشي بكب غماره', 'أ ح ب 2273', 1, '2022-08-01', '1444-01-03', '2020-09-05', '1442-01-17', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو شاحنه', 'ب ع ح 4137', 1, '2027-05-06', '1448-11-29', '2027-02-28', '1448-09-21', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو شاحنه', 'ب ع ح 4138', 1, '2027-05-06', '1448-11-29', '2027-02-26', '1448-09-19', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'أ ك د 4741', 1, '2024-12-02', '1446-06-01', '2026-12-15', '1448-07-06', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ب ك 3107', 1, '2024-12-06', '1446-06-05', '2026-06-24', '1448-01-09', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('هونداي توسان', 'ب ن م 9985', 1, '2027-01-28', '1448-08-20', '2026-06-26', '1448-01-11', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو دينا', 'أ د س 6005', 1, '2023-01-10', '1444-06-17', '2022-10-28', '1444-04-03', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ب ل 1618', 1, '2028-12-30', '1450-08-14', '2026-04-12', '1447-10-24', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ع أ 2263', 1, '2027-04-22', '1448-11-15', NULL, 'لم يتم الفحص ونقل الملكية', 'صالحة', '');
INSERT INTO vehicles (type, plate_number, company_id, form_expiry, form_expiry_hijri, inspection_expiry, inspection_expiry_hijri, condition, notes) VALUES ('ايسوزو بكب غمارتين', 'ب ع أ 2194', 1, '2027-04-25', '1448-11-18', NULL, 'لم يتم الفحص ونقل الملكية', 'صالحة', '');

-- المنصات والأنظمة
INSERT INTO platforms (name, entity, notes) VALUES ('وزارة الموارد البشرية', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة مقيم', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('التأمينات الاجتماعية', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة الجمارك ( فسح )', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة سابر', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('مصلحة الجمارك', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الدفاع المدني ( سلامة )', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الهيئة السعودية للمواصفات و المقاييس', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الهيئة العامة للنقل', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('بلدي لجميع الشركات', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة صناعي (مصنع نبات الأرض)', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('صندوق التنمية الصناعي', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('هيئة المدن ( رخصة التشغيل )', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة اعتماد', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الهيئة العامة للأرصاد وحماية البيئة', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('وزارة التجارة لجميع الشركات', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الزكاة و الدخل', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('شركة الاتصالات STC', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الغرفة التجارية', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة قوى', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة مدد', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('كاميرات مصنع نبات الأرض', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('أميل اعلان الوظائف', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة حصاد', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('العنوان الوطني المحلية الزراعية', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('العنوان الوطني مصنع نبات الأرض', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الصادرات السعودية', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('إيجار ( شبكة إيجار )', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('طاقات', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('موقع وظيفة كود', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الهيئة العامة للأحصاء', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة تم', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة فسح المصنع', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة هيئة المقاولين', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('شركة الكهرباء مصنع نبات الارض', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('شركة الكهرباء المحلية الزراعية', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('جدارة للتوظيف', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الغرفة التجارية مصنع نبات الأرض', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('الطابعة الجديد', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('منصة أجير', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('التأمين الطبي ( بوبا )', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('انترنت المكتب 1', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('انترنت المكتب 2', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('انترنت افاق شامل رقم الفاكس 2132603', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('شريحة بيانات انترنت خاص مكتب 17109', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('شريحة بيانات انترنت مكتب فودة', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('انترنت مكتب المحلية رقم 17103', '', '');
INSERT INTO platforms (name, entity, notes) VALUES ('GPS', '', '');

